### ISSUE TITLE
"Data read, but end of buffer not reached"

### ISSUE THREAD

**Issue by beaugunderson** [kriszyp/msgpackr#34]
My packed file has reached 1.4gb and I now get this error immediately upon attempting to read it:

```
Uncaught Error: Data read, but end of buffer not reached
    at checkedRead (/Users/beau/p/zed-run/node_modules/msgpackr/dist/node.cjs:130:10)
    at unpack (/Users/beau/p/zed-run/node_modules/msgpackr/dist/node.cjs:77:10)
    at exports.readPacked (/Users/beau/p/zed-run/utilities.js:223:32)
```

My `readPacked` function is simply: ```
unpack(fs.readFileSync(path));
```

**Comment by beaugunderson** [comment]
One clue--this was 1.4gb of a single object with ~66k keys. I just switched to serializing it as an array instead (and re-constructing the object for fast lookups after reading) and the issue went away. It will probably not be very common for someone to use msgpackr this way, but my dataset grew from something much more modest until it it exceeded whatever limit I hit here. :)

**Comment by kriszyp** [comment]
Try using `variableMapSize: true` option, otherwise msgpackr uses 16-bit map length (for performance). I'll add some notes to the docs to make this clearer.

**Comment by beaugunderson** [comment]
That has to be it, just crossed key 65,536 :)

**Comment by beaugunderson** [comment]
Hmm, there seems to be a gap in documentation.

Specifying `variableMapSize: true` on the decoder results in getting JavaScript `Map`s instead of JavaScript objects. The docs there say it only applies when useRecords is disabled, and mapAsObjects says it will default to enabled if useRecords is disabled.

**Comment by beaugunderson** [comment]
This does work though:

```js
  const unpackr = new Unpackr({ mapsAsObjects: true, variableMapSize: true });
```

**Comment by beaugunderson** [comment]
Hmm, `variableMapSize: true` also seems to cause decoding to take much longer than an additional 10%, it's gone from ~1 second to minutes for a 102mb msgpack file.

**Comment by kriszyp** [comment]
Do you have a test case for how to reproduce this? I am not seeing much performance difference using `variableMapSize: true` with my own data.

**Comment by beaugunderson** [comment]
Tried to come up with a test case just now that roughly mimics my object but it doesn't exhibit the same extreme unpacking time (I did measure how long it takes to unpack my 65k key object though, 64 seconds).

**Comment by beaugunderson** [comment]
Will clean up my current file and share it tomorrow, as well as compare the smaller than 65k non-`variableMapSize` version vs. the larger than 65k `variableMapSize` version directly.

**Comment by beaugunderson** [comment]
OK, so nowhere near as wide as a gulf as I thought! I think I probably compared my 1.4gb file, which has the same number of top-level keys but has a much higher proportion of arrays vs. nested keys, to this file, which is 102mb. The 1.4gb file takes 9 seconds, the 102mb file takes 64 seconds.

```
variableMapSize version
read in 63735ms
written in 20472ms

default options version
written in 13918ms
read in 51620ms```

I don't know if I crossed another performance threshold or what, but the 102mb file was much faster until recently; we can safely say the majority of the perf change wasn't from variableMapSize though.

**Comment by kriszyp** [comment]
Let me know if you do have any performance anomalies that I could reproduce.

**Comment by LekoArts** [comment]
Hi @kriszyp 👋 

We're running into this same error with Gatsby now. It seems that the recent `1.5.3` release caused this.

The output one gets is:

```shell
"internal-data-bridge" threw an error while running the sourceNodes lifecycle:

Data read, but end of buffer not reached

File: node_modules/gatsby/src/internal-plugins/internal-data-bridge/gatsby-node.js:55:5

  Error: Data read, but end of buffer not reached
  
  - node.cjs:178 checkedRead
    [browser-ssr-tsx]/[msgpackr]/dist/node.cjs:178:10
  
  - node.cjs:91 Packr.unpack
    [browser-ssr-tsx]/[msgpackr]/dist/node.cjs:91:10
  
  - node.cjs:150 Packr.decode
    [browser-ssr-tsx]/[msgpackr]/dist/node.cjs:150:15
  
  - index.js:440 Object.get
    [browser-ssr-tsx]/[lmdb-store]/index.js:440:63
  
  - caching.js:37 Object.get
    [browser-ssr-tsx]/[lmdb-store]/caching.js:37:17
  
  - lmdb-datastore.ts:148 Object.getNode
    [browser-ssr-tsx]/[gatsby]/src/datastore/lmdb/lmdb-datastore.ts:148:16
  
  - index.ts:18 getNode
    [browser-ssr-tsx]/[gatsby]/src/datastore/index.ts:18:18
  
  - public.js:767 createNode
    [browser-ssr-tsx]/[gatsby]/src/redux/actions/public.js:767:19
  
  - public.js:863 
    [browser-ssr-tsx]/[gatsby]/src/redux/actions/public.js:863:21
  
  - index.js:23 
    [browser-ssr-tsx]/[redux-thunk]/lib/index.js:23:18
  
  - redux.js:554 boundActionCreator
    [browser-ssr-tsx]/[redux]/lib/redux.js:554:12
  
  - api-runner-node.js:79 createNode
    [browser-ssr-tsx]/[gatsby]/src/utils/api-runner-node.js:79:20
  
  - gatsby-node.js:55 forEach
    [browser-ssr-tsx]/[gatsby]/src/internal-plugins/internal-data-bridge/gatsby-node.js:55:5
  
  - Array.forEach
  
  - gatsby-node.js:53 Object.exports.sourceNodes
    [browser-ssr-tsx]/[gatsby]/src/internal-plugins/internal-data-bridge/gatsby-node.js:53:20
  
  - api-runner-node.js:462 runAPI
    [browser-ssr-tsx]/[gatsby]/src/utils/api-runner-node.js:462:22
```

`internal-data-bridge` is something from us so that's why it is printing that.

You can reproduce this by running `npm init gatsby -y issue-34`, let the installation run and then do two `npm run build` in a row. On the second run you'll see this error. If you do a `npm run clean` in between (it removes the LMDB store data) in between, it works.

Let me know if you need any further information. Thanks a lot!

**Comment by kriszyp** [comment]
Thank you for the great detailed report, should be fixed in v1.5.4.

**Comment by LekoArts** [comment]
Awesome, thanks for the quick reply. Let me try it and I'll report back 👍

**Comment by alexbezhan** [comment]
I'm getting similar error.
Node server code:
```
const stream = new PackrStream({
        useRecords: true,
        bundleStrings: true,
    })
stream.pipe(response)
stream.write(...)
stream.end()
```

Client code:
```
const packr = new Packr({
    useRecords: true,
    bundleStrings: true, // client-side performance
})
const response = fetch(...)
const rows = packr.unpack(new Uint8Array(await response.arrayBuffer()))
```

Error:
```
Error: Data read, but end of buffer not reached {"id":0,"portfolio":"Z2 Force","campaign":"11_Profitable_Z2_Force","adGroup":"11_7_Profitable_Z2_For
    at checkedRead (st-table.iife.js?v=bbc4c8fdf7d4fa35e6fc73429d21fd76710cf374:195:18548)
    at Packr.unpack (st-table.iife.js?v=bbc4c8fdf7d4fa35e6fc73429d21fd76710cf374:195:16178)
    at Object.fetchRows [as queryFn] (st-table.iife.js?v=bbc4c8fdf7d4fa35e6fc73429d21fd76710cf374:289:50568)
```

**Comment by kriszyp** [comment]
@alexbezhan do you know if this can reproduced without streams (just pack and unpack)? Is any particular data necessary to reproduce?

**Comment by alexbezhan** [comment]
> @alexbezhan do you know if this can reproduced without streams (just pack and unpack)? Is any particular data necessary to reproduce?

Today I faced same issue. Now I can tell it can be reproduced without streams.
My case today was that I encoded object with structures, and then tried to decode it back with empty structures(issue was in my db not saving structures properly).

**Comment by Rossb0b** [comment]
@kriszyp 👋 went through the same issue using my [implementation](https://github.com/MyUnisoft/Redis/blob/v3.3.2/src/class/KVPeer.class.ts)

I didn't manage to reproduce it locally at this point, but the error occurred when deployed on a scaling environment.

I still have to investigate it as it isn't a huge priority on my side.

❤️
