### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by Zaseth** [kriszyp/msgpackr#4]
I receive an error when I try to install this dependency on Node v14.15.0. I don't know why this happens, I can install other native packages just fine.

```
C:\Users\Daan>npm i msgpackr

> msgpackr-extract@0.3.4 install C:\Users\Daan\node_modules\msgpackr-extract
> node-gyp-build


C:\Users\Daan\node_modules\msgpackr-extract>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targe
ts(46,5): error MSB8036: The Windows SDK version 10.0.18362.0 was not found. Install the required version of Windows SD
K or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget sol
ution". [C:\Users\Daan\node_modules\msgpackr-extract\build\msgpackr-extract.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Daan\node_modules\msgpackr-extract
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN Daan No description
npm WARN Daan No repository field.
npm WARN Daan No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: msgpackr-extract@0.3.4 (node_modules\msgpackr-extract):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: msgpackr-extract@0.3.4 install: `node-gyp-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ msgpackr@0.5.3
updated 1 package and audited 538 packages in 4.282s

36 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\Daan>
```

**Comment by kriszyp** [comment]
I don't know what could be specifying a particular Windows SDK version, I don't think there is anything in the builds that would dictate that. However, I published a new version with more complete prebuilds that should cover Node 14 (there is also a bug in prebuildify/node-abi that is causing prebuilds to not have the right versions, but I manually renamed them to get a working set of prebuilds). Can you try that and see if it works better for you (msgpackr 0.5.4 with msgpackr-extract 0.3.5)?

**Comment by Zaseth** [comment]
Works great now, thanks!
