### ISSUE TITLE
Not conform?

### ISSUE THREAD

**Issue by Uzlopak** [kriszyp/msgpackr#47]
I extended https://github.com/endel/msgpack-benchmark to handle msgpackr

added in benchmark.js  to implementations
```

    'msgpackr': {
      encode: require("msgpackr").encode,
      decode: require("msgpackr").decode
    },
```

It returns "Bad Implementation". The reasons seems, that msgpackr does not properly encodes/decodes 
`[1,2,3,"What a message pack!@",{"object":"options","here":10}]` is encoded/decoded to 
`[1,2,3,"What a message pack!@",{}]`

**Comment by Uzlopak** [comment]
I will create a git project later. Currently at my mobile.

**Comment by kriszyp** [comment]
Ok, even if you want to paste your code in here, I could take a look (again, the code above seems to work properly for me).

**Comment by Uzlopak** [comment]
https://github.com/Uzlopak/msgpack-benchmark

```

> msgpack-benchmark@1.0.0 start
> node ./benchmark.js


**sample-datatypes.json:**

/home/aras/Workspace/msgpack-benchmark/benchmark.js:69
    throw new Error("Bad implementation: " + name)
    ^

Error: Bad implementation: msgpackr
    at validate (/home/aras/Workspace/msgpack-benchmark/benchmark.js:69:11)
    at Object.<anonymous> (/home/aras/Workspace/msgpack-benchmark/benchmark.js:84:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

Hope this helps :)

**Comment by kriszyp** [comment]
@Uzlopak So the basic issue is that msgpackr's encode and decode functions consult their `this` object for settings, if they are called as a method, and in this case, using the created "implementation" object actually triggers different settings than the defaults settings, specifically it enables decoding MessagePack maps to JS Maps. Changing the code to directly call decode and encode, instead of continuing calling them as methods of the implementation object fixes the problem, and perhaps cleans-up and streamlines the benchmarking code a bit:
```
function validate(name, data, encoded) {
  let decode = implementations[name].decode
  if (JSON.stringify(data) !== JSON.stringify(decode(encoded))) {
    throw new Error("Bad implementation: " + name)
  }
}

for (var i = 0; i < sampleFiles.length; i++) {
  let data = JSON.parse(fs.readFileSync(sampleFiles[i], "utf-8").toString())
    , encodeSuite = new Benchmark.Suite()
    , decodeSuite = new Benchmark.Suite()

  console.log("")
  console.log("**" + sampleFiles[i] + ":**")
  console.log("")

  for (let name in implementations) {
    let toDecode = implementations[name].encode(data)
    validate(name, data, toDecode)
    let { encode, decode } = implementations[name]
    encodeSuite.add('(encode) ' + name, function () { encode(data) })
    decodeSuite.add('(decode) ' + name, function () { decode(toDecode) })
  }
```
That being said, I certainly recognize that msgpackr is a bit of an outlier in terms of that behavior. I will make a change in msgpackr to be more strict about only consulting `this` for setting if it is actually a Packr/Encoder instance.

**Comment by Uzlopak** [comment]
Hey! Thank you for the quick Analysis and solution finding. Looking forward for the release. 

I will benchmark later. Great job!

**Comment by kriszyp** [comment]
Ok, I published the fix in v1.5.0 (and verified it looks like it fixes msgpack-benchmark).

Are you going to submit a PR to endel's github to add msgpackr? That would be great if you could! It would also be great to include the sibling library cbor-x, which should also be vastly faster than the cbor libraries in msgpack-benchmark. Thank you!

**Comment by Uzlopak** [comment]
I created a PR for endels repo https://github.com/endel/msgpack-benchmark/pull/19

But I dont know if or when he would merge it.

On my Phenom X6 1055T with 32 GB DDR3 RAM and node 16.13.0 I get following results:


> msgpack-benchmark@1.0.0 start
> node ./benchmark.js


**sample-datatypes.json:**

```
(encode) msgpackr x 140,844 ops/sec ±1.47% (83 runs sampled)
(encode) @msgpack/msgpack x 69,662 ops/sec ±4.27% (79 runs sampled)
(encode) msgpack-js-v5 x 3,280 ops/sec ±59.36% (85 runs sampled)
(encode) msgpack-lite x 44,018 ops/sec ±3.11% (82 runs sampled)
(encode) msgpack5 x 9,422 ops/sec ±9.64% (82 runs sampled)
(encode) notepack x 65,312 ops/sec ±1.91% (90 runs sampled)
(encode) notepack.io x 73,966 ops/sec ±0.74% (93 runs sampled)
(encode) notepack.io (browser) x 59,273 ops/sec ±0.57% (89 runs sampled)
(encode) what-the-pack x 79,063 ops/sec ±0.85% (90 runs sampled)
(encode) what-the-pack (browser) x 87,080 ops/sec ±1.14% (91 runs sampled)
(encode) cbor (node) x 8,590 ops/sec ±9.44% (78 runs sampled)
(encode) cbor (browser) x 25,642 ops/sec ±0.50% (94 runs sampled)
(encode) cbor-x x 145,311 ops/sec ±0.67% (94 runs sampled)
(encode) JSON x 111,823 ops/sec ±0.47% (95 runs sampled)
```

```
(decode) msgpackr x 71,825 ops/sec ±0.51% (92 runs sampled)
(decode) @msgpack/msgpack x 55,713 ops/sec ±1.17% (88 runs sampled)
(decode) msgpack-js-v5 x 39,225 ops/sec ±0.52% (92 runs sampled)
(decode) msgpack-lite x 25,652 ops/sec ±0.76% (91 runs sampled)
(decode) msgpack5 x 14,007 ops/sec ±0.73% (89 runs sampled)
(decode) notepack x 45,985 ops/sec ±0.74% (92 runs sampled)
(decode) notepack.io x 67,266 ops/sec ±0.48% (94 runs sampled)
(decode) notepack.io (browser) x 39,457 ops/sec ±0.48% (93 runs sampled)
(decode) what-the-pack x 43,936 ops/sec ±0.45% (93 runs sampled)
(decode) what-the-pack (browser) x 43,292 ops/sec ±0.41% (94 runs sampled)
(decode) cbor (node) x 5,300 ops/sec ±1.16% (85 runs sampled)
(decode) cbor (browser) x 30,054 ops/sec ±0.47% (95 runs sampled)
(decode) cbor-x x 68,964 ops/sec ±0.48% (92 runs sampled)
(decode) JSON x 134,010 ops/sec ±0.44% (90 runs sampled)
```

**sample-small.json:**

```
(encode) msgpackr x 839,682 ops/sec ±0.83% (94 runs sampled)
(encode) @msgpack/msgpack x 239,070 ops/sec ±1.23% (66 runs sampled)
(encode) msgpack-js-v5 x 157,780 ops/sec ±0.50% (93 runs sampled)
(encode) msgpack-lite x 148,680 ops/sec ±4.66% (70 runs sampled)
(encode) msgpack5 x 50,706 ops/sec ±16.15% (70 runs sampled)
(encode) notepack x 631,651 ops/sec ±0.49% (92 runs sampled)
(encode) notepack.io x 665,922 ops/sec ±0.50% (90 runs sampled)
(encode) notepack.io (browser) x 386,590 ops/sec ±1.23% (83 runs sampled)
(encode) what-the-pack x 552,089 ops/sec ±0.63% (92 runs sampled)
(encode) what-the-pack (browser) x 654,697 ops/sec ±0.58% (90 runs sampled)
(encode) cbor (node) x 24,182 ops/sec ±16.91% (65 runs sampled)
(encode) cbor (browser) x 95,925 ops/sec ±21.52% (79 runs sampled)
(encode) cbor-x x 821,739 ops/sec ±1.00% (89 runs sampled)
(encode) JSON x 970,666 ops/sec ±0.62% (93 runs sampled)
```

```
(decode) msgpackr x 969,689 ops/sec ±0.60% (91 runs sampled)
(decode) @msgpack/msgpack x 456,609 ops/sec ±0.61% (87 runs sampled)
(decode) msgpack-js-v5 x 418,528 ops/sec ±0.51% (91 runs sampled)
(decode) msgpack-lite x 230,700 ops/sec ±0.53% (92 runs sampled)
(decode) msgpack5 x 105,387 ops/sec ±0.67% (89 runs sampled)
(decode) notepack x 648,988 ops/sec ±0.58% (92 runs sampled)
(decode) notepack.io x 714,284 ops/sec ±0.72% (92 runs sampled)
(decode) notepack.io (browser) x 535,683 ops/sec ±0.59% (87 runs sampled)
(decode) what-the-pack x 472,014 ops/sec ±0.82% (91 runs sampled)
(decode) what-the-pack (browser) x 482,011 ops/sec ±0.60% (93 runs sampled)
(decode) cbor (node) x 26,345 ops/sec ±0.91% (85 runs sampled)
(decode) cbor (browser) x 367,068 ops/sec ±0.48% (94 runs sampled)
(decode) cbor-x x 1,002,509 ops/sec ±0.59% (92 runs sampled)
(decode) JSON x 826,515 ops/sec ±0.70% (91 runs sampled)
```

**sample-medium.json:**

```
(encode) msgpackr x 409,572 ops/sec ±0.59% (94 runs sampled)
(encode) @msgpack/msgpack x 175,386 ops/sec ±4.04% (70 runs sampled)
(encode) msgpack-js-v5 x 44,929 ops/sec ±0.80% (90 runs sampled)
(encode) msgpack-lite x 95,912 ops/sec ±3.52% (83 runs sampled)
(encode) msgpack5 x 30,970 ops/sec ±1.66% (86 runs sampled)
(encode) notepack x 56,660 ops/sec ±98.53% (85 runs sampled)
(encode) notepack.io x 273,321 ops/sec ±0.59% (91 runs sampled)
(encode) notepack.io (browser) x 195,101 ops/sec ±0.99% (87 runs sampled)
(encode) what-the-pack x 211,149 ops/sec ±0.56% (95 runs sampled)
(encode) what-the-pack (browser) x 249,583 ops/sec ±0.57% (93 runs sampled)
(encode) cbor (node) x 20,887 ops/sec ±1.85% (80 runs sampled)
(encode) cbor (browser) x 98,213 ops/sec ±0.92% (88 runs sampled)
(encode) cbor-x x 388,615 ops/sec ±0.80% (92 runs sampled)
(encode) JSON x 506,775 ops/sec ±0.64% (93 runs sampled)
```

```
(decode) msgpackr x 324,032 ops/sec ±0.53% (91 runs sampled)
(decode) @msgpack/msgpack x 218,478 ops/sec ±0.67% (90 runs sampled)
(decode) msgpack-js-v5 x 124,818 ops/sec ±0.86% (91 runs sampled)
(decode) msgpack-lite x 71,204 ops/sec ±0.53% (91 runs sampled)
(decode) msgpack5 x 48,045 ops/sec ±0.89% (86 runs sampled)
(decode) notepack x 157,979 ops/sec ±0.60% (94 runs sampled)
(decode) notepack.io x 255,243 ops/sec ±0.76% (90 runs sampled)
(decode) notepack.io (browser) x 178,754 ops/sec ±0.43% (92 runs sampled)
(decode) what-the-pack x 149,329 ops/sec ±0.56% (90 runs sampled)
(decode) what-the-pack (browser) x 141,676 ops/sec ±0.52% (92 runs sampled)
(decode) cbor (node) x 12,242 ops/sec ±1.28% (80 runs sampled)
(decode) cbor (browser) x 140,581 ops/sec ±0.46% (93 runs sampled)
(decode) cbor-x x 319,798 ops/sec ±0.54% (89 runs sampled)
(decode) JSON x 431,752 ops/sec ±0.82% (93 runs sampled)
```

**sample-large.json:**

```
(encode) msgpackr x 18,645 ops/sec ±0.67% (94 runs sampled)
(encode) @msgpack/msgpack x 10,418 ops/sec ±1.43% (88 runs sampled)
(encode) msgpack-js-v5 x 2,119 ops/sec ±1.49% (85 runs sampled)
(encode) msgpack-lite x 5,855 ops/sec ±1.95% (84 runs sampled)
(encode) msgpack5 x 1,032 ops/sec ±59.29% (53 runs sampled)
(encode) notepack x 1,868 ops/sec ±47.10% (75 runs sampled)
(encode) notepack.io x 10,372 ops/sec ±0.60% (91 runs sampled)
(encode) notepack.io (browser) x 8,948 ops/sec ±0.59% (92 runs sampled)
(encode) what-the-pack x 9,608 ops/sec ±0.83% (92 runs sampled)
(encode) what-the-pack (browser) x 10,745 ops/sec ±0.78% (92 runs sampled)
(encode) cbor (node) x 1,750 ops/sec ±1.13% (88 runs sampled)
(encode) cbor (browser) x 3,485 ops/sec ±0.82% (90 runs sampled)
(encode) cbor-x x 17,987 ops/sec ±0.78% (94 runs sampled)
(encode) JSON x 23,564 ops/sec ±0.73% (93 runs sampled)
```

```
(decode) msgpackr x 19,934 ops/sec ±0.74% (91 runs sampled)
(decode) @msgpack/msgpack x 6,048 ops/sec ±0.89% (86 runs sampled)
(decode) msgpack-js-v5 x 5,798 ops/sec ±0.88% (87 runs sampled)
(decode) msgpack-lite x 3,403 ops/sec ±0.61% (90 runs sampled)
(decode) msgpack5 x 2,877 ops/sec ±1.04% (89 runs sampled)
(decode) notepack x 7,420 ops/sec ±1.07% (91 runs sampled)
(decode) notepack.io x 10,710 ops/sec ±0.92% (91 runs sampled)
(decode) notepack.io (browser) x 5,218 ops/sec ±1.03% (89 runs sampled)
(decode) what-the-pack x 6,754 ops/sec ±1.34% (88 runs sampled)
(decode) what-the-pack (browser) x 6,847 ops/sec ±0.72% (90 runs sampled)
(decode) cbor (node) x 651 ops/sec ±2.62% (73 runs sampled)
(decode) cbor (browser) x 4,271 ops/sec ±0.77% (88 runs sampled)
(decode) cbor-x x 18,473 ops/sec ±0.70% (91 runs sampled)
(decode) JSON x 22,594 ops/sec ±1.05% (88 runs sampled)
```

Which is really good. msgpackr is definetly the fastest serializer. I know JSON is according to this benchmark faster but this is because endels benchmark compares JSON.stringify with other serializers. As you know JSON.stringify create a string and not a Buffer. If you modify JSON encode to create buffers 

`      encode: (data) => Buffer.from(JSON.stringify(data)),`

then JSON get slower than msgpackr.

Thank you very much for your hard work.

**Comment by Uzlopak** [comment]
With the suggested change to JSON i get this benchmarks:


> msgpack-benchmark@1.0.0 start
> node ./benchmark.js


**sample-datatypes.json:**

```
(encode) msgpackr x 139,129 ops/sec ±1.16% (86 runs sampled)
(encode) @msgpack/msgpack x 65,550 ops/sec ±3.55% (77 runs sampled)
(encode) msgpack-js-v5 x 2,323 ops/sec ±57.21% (78 runs sampled)
(encode) msgpack-lite x 46,426 ops/sec ±2.61% (90 runs sampled)
(encode) msgpack5 x 9,186 ops/sec ±3.05% (78 runs sampled)
(encode) notepack x 61,349 ops/sec ±1.45% (89 runs sampled)
(encode) notepack.io x 74,865 ops/sec ±0.85% (90 runs sampled)
(encode) notepack.io (browser) x 57,920 ops/sec ±0.39% (94 runs sampled)
(encode) what-the-pack x 76,216 ops/sec ±0.95% (93 runs sampled)
(encode) what-the-pack (browser) x 83,645 ops/sec ±0.96% (90 runs sampled)
(encode) cbor (node) x 8,430 ops/sec ±9.17% (80 runs sampled)
(encode) cbor (browser) x 24,933 ops/sec ±0.20% (94 runs sampled)
(encode) cbor-x x 144,988 ops/sec ±0.39% (95 runs sampled)
(encode) JSON x 66,388 ops/sec ±0.25% (90 runs sampled)
```

```
(decode) msgpackr x 73,920 ops/sec ±0.27% (91 runs sampled)
(decode) @msgpack/msgpack x 54,639 ops/sec ±1.03% (91 runs sampled)
(decode) msgpack-js-v5 x 38,303 ops/sec ±0.74% (92 runs sampled)
(decode) msgpack-lite x 25,116 ops/sec ±0.23% (93 runs sampled)
(decode) msgpack5 x 13,599 ops/sec ±0.33% (92 runs sampled)
(decode) notepack x 44,812 ops/sec ±0.28% (91 runs sampled)
(decode) notepack.io x 68,273 ops/sec ±0.18% (96 runs sampled)
(decode) notepack.io (browser) x 41,617 ops/sec ±0.39% (90 runs sampled)
(decode) what-the-pack x 38,571 ops/sec ±0.28% (89 runs sampled)
(decode) what-the-pack (browser) x 43,589 ops/sec ±0.24% (93 runs sampled)
(decode) cbor (node) x 5,151 ops/sec ±0.95% (83 runs sampled)
(decode) cbor (browser) x 29,525 ops/sec ±0.19% (94 runs sampled)
(decode) cbor-x x 71,799 ops/sec ±0.24% (95 runs sampled)
(decode) JSON x 80,697 ops/sec ±0.60% (94 runs sampled)
```

**sample-small.json:**

```
(encode) msgpackr x 807,259 ops/sec ±0.51% (92 runs sampled)
(encode) @msgpack/msgpack x 243,440 ops/sec ±1.26% (64 runs sampled)
(encode) msgpack-js-v5 x 142,795 ops/sec ±0.33% (92 runs sampled)
(encode) msgpack-lite x 151,449 ops/sec ±4.60% (72 runs sampled)
(encode) msgpack5 x 47,999 ops/sec ±15.02% (73 runs sampled)
(encode) notepack x 614,253 ops/sec ±0.34% (92 runs sampled)
(encode) notepack.io x 649,800 ops/sec ±0.28% (93 runs sampled)
(encode) notepack.io (browser) x 400,653 ops/sec ±1.22% (84 runs sampled)
(encode) what-the-pack x 508,973 ops/sec ±0.52% (90 runs sampled)
(encode) what-the-pack (browser) x 566,618 ops/sec ±0.44% (94 runs sampled)
(encode) cbor (node) x 23,353 ops/sec ±16.68% (66 runs sampled)
(encode) cbor (browser) x 97,967 ops/sec ±24.79% (81 runs sampled)
(encode) cbor-x x 866,397 ops/sec ±0.63% (92 runs sampled)
(encode) JSON x 458,074 ops/sec ±0.49% (93 runs sampled)
```

```
(decode) msgpackr x 933,193 ops/sec ±0.55% (91 runs sampled)
(decode) @msgpack/msgpack x 447,230 ops/sec ±0.35% (88 runs sampled)
(decode) msgpack-js-v5 x 394,415 ops/sec ±0.33% (91 runs sampled)
(decode) msgpack-lite x 223,838 ops/sec ±0.31% (93 runs sampled)
(decode) msgpack5 x 102,674 ops/sec ±0.49% (88 runs sampled)
(decode) notepack x 615,905 ops/sec ±0.47% (93 runs sampled)
(decode) notepack.io x 690,739 ops/sec ±0.56% (92 runs sampled)
(decode) notepack.io (browser) x 546,813 ops/sec ±0.30% (91 runs sampled)
(decode) what-the-pack x 456,431 ops/sec ±0.73% (92 runs sampled)
(decode) what-the-pack (browser) x 449,642 ops/sec ±0.43% (94 runs sampled)
(decode) cbor (node) x 26,058 ops/sec ±0.62% (86 runs sampled)
(decode) cbor (browser) x 363,032 ops/sec ±0.23% (94 runs sampled)
(decode) cbor-x x 980,254 ops/sec ±0.66% (90 runs sampled)
(decode) JSON x 420,706 ops/sec ±0.42% (94 runs sampled)
```

**sample-medium.json:**

```
(encode) msgpackr x 399,311 ops/sec ±0.94% (93 runs sampled)
(encode) @msgpack/msgpack x 173,109 ops/sec ±3.88% (73 runs sampled)
(encode) msgpack-js-v5 x 43,363 ops/sec ±0.70% (89 runs sampled)
(encode) msgpack-lite x 95,830 ops/sec ±3.07% (86 runs sampled)
(encode) msgpack5 x 29,463 ops/sec ±1.55% (90 runs sampled)
(encode) notepack x 176,479 ops/sec ±1.10% (88 runs sampled)
(encode) notepack.io x 175,347 ops/sec ±47.81% (88 runs sampled)
(encode) notepack.io (browser) x 200,236 ops/sec ±0.90% (89 runs sampled)
(encode) what-the-pack x 204,301 ops/sec ±0.57% (93 runs sampled)
(encode) what-the-pack (browser) x 229,094 ops/sec ±0.57% (91 runs sampled)
(encode) cbor (node) x 7,757 ops/sec ±20.14% (31 runs sampled)
(encode) cbor (browser) x 93,247 ops/sec ±9.67% (84 runs sampled)
(encode) cbor-x x 405,651 ops/sec ±0.73% (91 runs sampled)
(encode) JSON x 312,343 ops/sec ±0.61% (91 runs sampled)
```

```
(decode) msgpackr x 316,737 ops/sec ±0.54% (92 runs sampled)
(decode) @msgpack/msgpack x 213,130 ops/sec ±0.57% (91 runs sampled)
(decode) msgpack-js-v5 x 119,609 ops/sec ±0.66% (91 runs sampled)
(decode) msgpack-lite x 68,140 ops/sec ±0.33% (92 runs sampled)
(decode) msgpack5 x 47,641 ops/sec ±0.67% (89 runs sampled)
(decode) notepack x 140,684 ops/sec ±0.44% (90 runs sampled)
(decode) notepack.io x 250,190 ops/sec ±0.50% (94 runs sampled)
(decode) notepack.io (browser) x 177,330 ops/sec ±0.23% (96 runs sampled)
(decode) what-the-pack x 137,025 ops/sec ±0.44% (92 runs sampled)
(decode) what-the-pack (browser) x 136,872 ops/sec ±0.41% (94 runs sampled)
(decode) cbor (node) x 12,141 ops/sec ±1.20% (81 runs sampled)
(decode) cbor (browser) x 139,663 ops/sec ±0.34% (95 runs sampled)
(decode) cbor-x x 316,693 ops/sec ±0.62% (91 runs sampled)
(decode) JSON x 291,155 ops/sec ±0.86% (90 runs sampled)
```

**sample-large.json:**

```
(encode) msgpackr x 18,193 ops/sec ±0.52% (96 runs sampled)
(encode) @msgpack/msgpack x 10,393 ops/sec ±0.96% (90 runs sampled)
(encode) msgpack-js-v5 x 2,161 ops/sec ±0.69% (92 runs sampled)
(encode) msgpack-lite x 6,798 ops/sec ±1.34% (88 runs sampled)
(encode) msgpack5 x 973 ops/sec ±62.80% (54 runs sampled)
(encode) notepack x 3,633 ops/sec ±58.82% (90 runs sampled)
(encode) notepack.io x 10,098 ops/sec ±0.34% (95 runs sampled)
(encode) notepack.io (browser) x 9,190 ops/sec ±0.34% (94 runs sampled)
(encode) what-the-pack x 9,378 ops/sec ±0.50% (94 runs sampled)
(encode) what-the-pack (browser) x 10,701 ops/sec ±0.50% (94 runs sampled)
(encode) cbor (node) x 1,770 ops/sec ±0.94% (91 runs sampled)
(encode) cbor (browser) x 3,593 ops/sec ±0.52% (92 runs sampled)
(encode) cbor-x x 18,182 ops/sec ±0.49% (96 runs sampled)
(encode) JSON x 11,160 ops/sec ±0.43% (90 runs sampled)
```

```
(decode) msgpackr x 19,424 ops/sec ±0.41% (94 runs sampled)
(decode) @msgpack/msgpack x 6,276 ops/sec ±0.93% (87 runs sampled)
(decode) msgpack-js-v5 x 5,706 ops/sec ±1.10% (88 runs sampled)
(decode) msgpack-lite x 3,311 ops/sec ±0.29% (92 runs sampled)
(decode) msgpack5 x 3,019 ops/sec ±0.53% (93 runs sampled)
(decode) notepack x 7,066 ops/sec ±0.49% (94 runs sampled)
(decode) notepack.io x 10,121 ops/sec ±0.49% (95 runs sampled)
(decode) notepack.io (browser) x 5,470 ops/sec ±0.86% (91 runs sampled)
(decode) what-the-pack x 6,728 ops/sec ±0.47% (94 runs sampled)
(decode) what-the-pack (browser) x 6,663 ops/sec ±0.44% (92 runs sampled)
(decode) cbor (node) x 658 ops/sec ±2.49% (76 runs sampled)
(decode) cbor (browser) x 4,348 ops/sec ±0.47% (94 runs sampled)
(decode) cbor-x x 19,562 ops/sec ±0.49% (93 runs sampled)
(decode) JSON x 15,256 ops/sec ±0.46% (93 runs sampled)
```

**Comment by Uzlopak** [comment]
TBH, I never heard before of cbor. I researched and as the performance of cbor-x and msgpackr is about the same I think I switch to cbor-x. It seems to be the right choice. Or do you have some recommendation?

Again: Great Job.

**Comment by kriszyp** [comment]
Thank you! I don't have any strong recommendation one or the other. CBOR has a good standardization effort and I believe it is starting to get increasing adoption, so it is a good choice as well.
